# Generated by Django 6.0.3 on 2026-03-13 13:36

import devices.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('prefix', models.CharField(help_text='Short prefix for asset tags, e.g. ATT, MIX, CBL', max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'device categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_tag', models.CharField(blank=True, help_text='Auto-generated if left blank, e.g. ATT-001', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model_number', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency_min_hz', models.BigIntegerField(blank=True, help_text='Minimum frequency in Hz', null=True)),
                ('frequency_max_hz', models.BigIntegerField(blank=True, help_text='Maximum frequency in Hz', null=True)),
                ('port_count', models.PositiveIntegerField(blank=True, null=True)),
                ('impedance_ohms', models.FloatField(blank=True, default=50.0, null=True)),
                ('max_power_dbm', models.FloatField(blank=True, help_text='Maximum input power in dBm', null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicecategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DevicePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=devices.models.device_photo_path)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='devices.device')),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=devices.models.device_document_path)),
                ('title', models.CharField(max_length=300)),
                ('doc_type', models.CharField(choices=[('datasheet', 'Datasheet'), ('manual', 'Manual'), ('app_note', 'Application Note'), ('other', 'Other')], default='other', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='devices.device')),
            ],
            options={
                'ordering': ['doc_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TouchstoneFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=devices.models.device_touchstone_path)),
                ('original_filename', models.CharField(max_length=300)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Key-value parameters, e.g. {"attenuation": "10 dB"}')),
                ('port_count', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency_min_hz', models.BigIntegerField(blank=True, null=True)),
                ('frequency_max_hz', models.BigIntegerField(blank=True, null=True)),
                ('frequency_npoints', models.PositiveIntegerField(blank=True, null=True)),
                ('impedance_ohms', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touchstone_files', to='devices.device')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
