# Generated by Django 6.0.3 on 2026-03-13 15:07

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_add_more_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, help_text='External URL (use instead of or in addition to a file upload)', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('datasheet', 'Datasheet'), ('manual', 'Manual'), ('app_note', 'Application Note'), ('measurement', 'Measurement'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, upload_to=devices.models.device_document_path),
        ),
    ]
